baseURL = "https://phsilva.dev/"
title = "phsilva.dev"

languageCode = "en-us"
defaultcontentlanguage = "en-us"

theme = "hugo-coder"

paginate = 20

googleAnalytics = "UA-3062863-5"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
    author = "Paulo Henrique Silva"
    description = "pH's personal website"
    keywords = "blog,developer,personal"
    info = "Senior Software Engineer"
    avatarurl = "images/avatar.jpg"
    footercontent = "wash your hands"

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

